# Generated by Django 5.2.6 on 2025-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the camera', max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of the camera', max_length=200, null=True)),
                ('stream_url', models.CharField(help_text='RTSP URL or device index (e.g., rtsp://... or 0, 1, 2)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the camera is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
    ]
