# Generated by Django 5.2.6 on 2025-10-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0002_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Captured image of the violation', upload_to='violations/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(help_text='Detection confidence score (0-1)')),
                ('bbox_x1', models.IntegerField(help_text='Bounding box top-left X coordinate')),
                ('bbox_y1', models.IntegerField(help_text='Bounding box top-left Y coordinate')),
                ('bbox_x2', models.IntegerField(help_text='Bounding box bottom-right X coordinate')),
                ('bbox_y2', models.IntegerField(help_text='Bounding box bottom-right Y coordinate')),
                ('reviewed', models.BooleanField(default=False, help_text='Whether admin has reviewed this violation')),
                ('sent_to_admin', models.BooleanField(default=False, help_text='Whether this has been sent to admin')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this violation', null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_snapshots', to='gatewatch_api.camera')),
            ],
            options={
                'verbose_name': 'Violation Snapshot',
                'verbose_name_plural': 'Violation Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
