# Generated by Django 5.2.6 on 2025-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0003_violationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationsnapshot',
            name='department',
            field=models.CharField(blank=True, choices=[('SAS', 'School of Arts and Sciences'), ('STCS', 'School of Technology and Computer Studies'), ('SOE', 'School of Engineering'), ('STE', 'School of Teacher Education'), ('SCJE', 'School of Criminal Justice Education'), ('SME', 'School of Management and Entrepreneurship'), ('SNHS', 'School of Nursing and Health Sciences'), ('LHS', 'Laboratory High School')], help_text="Student's department/school", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text="Student's gender", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='identified',
            field=models.BooleanField(default=False, help_text='Whether student has been identified'),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='student_name',
            field=models.CharField(blank=True, help_text='Name of the student', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this violation', null=True),
        ),
    ]
