# Generated by Django 5.2.6 on 2025-10-22 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0004_violationsnapshot_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='Whether the camera is currently being streamed by security'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_streamed_at',
            field=models.DateTimeField(blank=True, help_text='When the stream was last started', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_streamed_by',
            field=models.ForeignKey(blank=True, help_text='User who last started this stream', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streamed_cameras', to=settings.AUTH_USER_MODEL),
        ),
    ]
