# Generated by Django 5.2.6 on 2025-10-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0005_camera_is_streaming_camera_last_streamed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non-compliant', 'Non-Compliant')], help_text='Compliance status', max_length=20)),
                ('confidence', models.FloatField(help_text='Detection confidence score (0-1)')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_detections', to='gatewatch_api.camera')),
                ('violation_snapshot', models.OneToOneField(blank=True, help_text='Linked violation snapshot if status is non-compliant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_detection', to='gatewatch_api.violationsnapshot')),
            ],
            options={
                'verbose_name': 'Compliance Detection',
                'verbose_name_plural': 'Compliance Detections',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['camera', 'timestamp'], name='gatewatch_a_camera__bcbbb9_idx'), models.Index(fields=['status', 'timestamp'], name='gatewatch_a_status_138bd6_idx')],
            },
        ),
    ]
