# Generated by Django 5.2.6 on 2025-10-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0006_compliancedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Token for password reset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, help_text='Token expiration time', null=True),
        ),
    ]
