# Generated by Django 5.2.6 on 2025-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0007_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token_expiry',
        ),
    ]
