# Generated by Django 5.2.6 on 2025-12-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0008_remove_user_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationsnapshot',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID number', max_length=20, null=True),
        ),
    ]
