# Generated by Django 5.2.6 on 2025-12-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0009_violationsnapshot_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedetection',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_detections', to='gatewatch_api.camera'),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_snapshots', to='gatewatch_api.camera'),
        ),
    ]
