# Generated by Django 5.2.6 on 2025-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0010_alter_compliancedetection_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationsnapshot',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for deletion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='bbox_x1',
            field=models.IntegerField(default=0, help_text='Bounding box top-left X coordinate'),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='bbox_x2',
            field=models.IntegerField(default=0, help_text='Bounding box bottom-right X coordinate'),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='bbox_y1',
            field=models.IntegerField(default=0, help_text='Bounding box top-left Y coordinate'),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='bbox_y2',
            field=models.IntegerField(default=0, help_text='Bounding box bottom-right Y coordinate'),
        ),
        migrations.AlterField(
            model_name='violationsnapshot',
            name='image',
            field=models.ImageField(blank=True, help_text='Captured image of the violation (local fallback)', null=True, upload_to='violations/%Y/%m/%d/'),
        ),
    ]
