# Generated by Django on 2025-12-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(help_text='Name for the camera', max_length=100),
        ),
    ]
