# Generated by Django 5.2.6 on 2026-01-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewatch_api', '0013_remove_camera_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the student', max_length=200)),
                ('student_id', models.CharField(blank=True, help_text='Student ID number (optional)', max_length=20, null=True)),
                ('department', models.CharField(blank=True, help_text="Student's department", max_length=10, null=True)),
                ('gender', models.CharField(blank=True, help_text="Student's gender", max_length=1, null=True)),
                ('violation_type', models.CharField(choices=[('improper_uniform', 'Improper Uniform'), ('missing_id', 'Missing ID'), ('civilian_clothes', 'Civilian Clothes'), ('missing_uniform_top', 'Missing Uniform Top'), ('other', 'Other')], default='improper_uniform', help_text='Type of uniform violation', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary image URL', max_length=500, null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID', max_length=255, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When the warning was issued')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the warning', null=True)),
                ('is_expired', models.BooleanField(default=False, help_text='Whether this warning has expired')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='gatewatch_api.camera')),
                ('detected_by', models.ForeignKey(blank=True, help_text='Security personnel who issued the warning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warning',
                'verbose_name_plural': 'Warnings',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['student_name', 'detected_at'], name='gatewatch_a_student_11cd99_idx'), models.Index(fields=['is_expired', 'detected_at'], name='gatewatch_a_is_expi_6d2d1e_idx')],
            },
        ),
    ]
